FROM python:3.9

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
	build-essential autoconf libtool pkg-config git software-properties-common curl \
	apt-transport-https ca-certificates curl wget make libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm \
	libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
	libxml2 libxslt1.1 libgpgme-dev libldap2-dev libsasl2-dev swig libtiff5-dev libopenjp2-7-dev \
	libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
	libharfbuzz-dev libfribidi-dev libxcb1-dev build-essential cargo python3-dev python3-setuptools
	
# Copy python dependencies
COPY requirements.txt .
COPY requirements-dev.txt .
COPY ./hack/verify-requirements.sh .
COPY Makefile .

# upgrade pip and install required python modules
RUN pip install --upgrade pip && \
    pip install -U setuptools wheel Cython==3.0.0a9 launchpadlib==1.11.0 && \
	./hack/verify-requirements.sh && \
	pip install -r ./requirements-dev.txt --ignore-installed